FROM yourls:latest

WORKDIR /var/www/html

ADD https://github.com/adigitalife/yourls-case-insensitive/tarball/master     \
    /opt/yourls-case-insensitive.tar.gz    

RUN for i in $(ls /opt/*.tar.gz); do                                          \
      plugin_name="$(basename ${i} '.tar.gz')"                              ; \
      mkdir -p user/plugins/${plugin_name}                                  ; \
      tar zxvf /opt/${plugin_name}.tar.gz                                     \
        --strip-components=1                                                  \
        -C user/plugins/${plugin_name}                                      ; \
    done
    
RUN rm user/plugins/*.md

RUN chown -R www-data:www-data user/plugins
